#!/bin/sh
#
# Run tests locally before push.
# Pre-push expects application to be running on port 3000 and backend on port 5000.

currentfile=$(readlink -f "$0")			# Location of this file
hookspath=$(dirname "$currentfile")		# Location of git-hooks folder
projectpath=$(dirname "$hookspath")		# Location of project folder

# Check if frontend application is running
if ! lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null; then
	echo "Frontend is not running"
	exit 1
fi

# Check if backend application is running
if ! lsof -Pi :5000 -sTCP:LISTEN -t >/dev/null; then
	echo "Backend is not running"
	exit 1
fi

echo "------------------------------"
echo "Running the pre-push e2e tests"
echo "------------------------------"

cd $projectpath/frontend

# Run Cypress tests with headless chrome
$projectpath/frontend/node_modules/.bin/cypress run \
	--spec "$projectpath/frontend/cypress/e2e/fail.cy.js" \
	--browser chrome
