#!/bin/sh

currentfile=$(readlink -f "$0")
hookspath=$(dirname "$currentfile")
projectpath=$(dirname "$hookspath")

echo "$projectpath"

echo "Running docker compose"
docker compose -f "$projectpath/docker-compose.yml" up --build &

sleep 30

echo "Running e2e tests"
export $(grep -v '^#' backend/.env | xargs -d '\n')
echo $TMCUSERNAME 

cd $projectpath/frontend

echo $(pwd)

$projectpath/frontend/node_modules/.bin/cypress run --browser chrome --env tmcusername=$TMCUSERNAME,tmcpassword=$TMCPASSWORD

docker compose stop