services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-db-data:
    name: postgres-db-data
