services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    depends_on:
      - backend
      
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend