/// <reference types="Cypress" />

describe('TMC-Coach set deadline', { defaultCommandTimeout: 8000 }, () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000')
  })
  it('logged in user can go to the set deadline page', () => {
    cy.get('input[name=username]').type(Cypress.env('tmcusername'))
    cy.get('input[name=password]').type(Cypress.env('tmcpassword'))
    cy.get('button[type=submit]').click()
    cy.url().should('not.include', '/login')
    cy.visit('http://localhost:3000/orgs')
    cy.visit('http://localhost:3000/orgs/mooc')
    cy.visit('http://localhost:3000/orgs/courses/277/set_deadline')
    cy.contains('Set deadline for course 2013 Object-oriented programming, part 1').should('exist')
    cy.contains('Choose the deadline for this course').should('exist')
  })
  it('logged out user can not go to the set deadline page', () => {
    cy.visit('http://localhost:3000/orgs/courses/277/set_deadline')
    cy.url().should('include', '/login')
  })
  it('logged in user can set deadline', () => {
    cy.get('input[name=username]').type(Cypress.env('tmcusername'))
    cy.get('input[name=password]').type(Cypress.env('tmcpassword'))
    cy.get('button[type=submit]').click()
    cy.url().should('not.include', '/login')
    window.localStorage.setItem('loggedInUser', Cypress.env('tmcusername'))
    cy.visit('http://localhost:3000/orgs/courses/277/set_deadline')
    cy.get('button.react-datepicker__navigation.react-datepicker__navigation--next').click()
    cy.contains('4').click()
    cy.get('button[value=set_deadline]').click()
    expect(localStorage.getItem('loggedInUser')).to.eq(Cypress.env('tmcusername'))
    cy.visit('http://localhost:3000/orgs/courses/277/set_deadline')
    cy.contains('2023-03-04').should('exist')
  })
  it('datapicker can be clicked', () => {
    cy.get('input[name=username]').type(Cypress.env('tmcusername'))
    cy.get('input[name=password]').type(Cypress.env('tmcpassword'))
    cy.get('button[type=submit]').click()
    cy.url().should('not.include', '/login')
    cy.visit('http://localhost:3000/orgs/courses/277/set_deadline')
    cy.get('button.react-datepicker__navigation.react-datepicker__navigation--next').click().click()
    cy.contains('18').click()
    cy.get('button.react-datepicker__navigation.react-datepicker__navigation--previous').click()
    cy.contains('28').click()
  })
  it('set deadline -page will show no deadlines is there is none', () => {
    cy.get('input[name=username]').type(Cypress.env('tmcusername'))
    cy.get('input[name=password]').type(Cypress.env('tmcpassword'))
    cy.get('button[type=submit]').click()
    cy.url().should('not.include', '/login')
    cy.visit('http://localhost:3000/orgs/courses/1113/set_deadline')
    cy.contains('No deadlines chosen for this course').should('exist')
  })
})
