name: Linters

on: [push, pull_request]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint ./app.py

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run ESLint 
        run: npm run lint
  
  cypress-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start docker containers
        run: docker-compose -f docker-compose.yml up --build --detach

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./frontend
          browser: chrome
          env: tmcusername=${{ secrets.TMCUSERNAME }},tmcpassword=${{ secrets.TMCPASSWORD }}
