name: Linters

on: [push, pull_request]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          pylint ./app.py

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run ESLint 
        run: npm run lint
  
  robot-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start backend for robot
        run: |
          python wsgi.py &
          sleep 2
      - name: Start frontend for robot
        run: |
          cd ../frontend
          npm install
          npm start &
          sleep 4
      - name: Run robot tests
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "*** Variables ***" > ../frontend/robot-tests/login_resource.robot
          echo '${USERNAME}'"\\t${{ secrets.USERNAME }}" >> ../frontend/robot-tests/login_resource.robot
          echo '${PASSWORD}'"\\t${{ secrets.PASSWORD }}" >> ../frontend/robot-tests/login_resource.robot
          python -m pip install --upgrade pip
          pip install -r ../frontend/robot-tests/requirements.txt
          robot ../frontend/robot-tests
